### PR TITLE
Parser: Support double quoted strings.

### PR DESCRIPTION
**Pull request by Acconut**
First of all: Nice project :+1:

Anyway, this PR adds support for double quoted strings for tagua-vm/tagua-vm#30.
It is not complete but provides the first steps.

### CODE REVIEW

**Comment by Hywan** [comment]
Hey :-),

Thank you for the PR but this is more difficult to implement double quote strings because the content can be very different. My goal is to postpone this task, and work on it when variables & co. will be supported.

What do you think? I prefer to have something complete than something not completely implemented.

**Comment by Acconut** [comment]
This absolutely makes sense. Do you have any plan on when and how to continue with developing the Tagua VM?

**Comment by Hywan** [comment]
Yes sure. I am setting a campaign for a crowdfunding around Tagua VM. You will hear about it soon I presume :-).

**Comment by Acconut** [comment]
Wow, this sounds pretty incredible. Looking forward to this announcement and I wish you good luck with it :+1:

**Comment by Hywan** [comment]
Thank you!

**Pull request closed without merging**
